# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abelov <abelov@student.42london.com>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/03/20 05:43:01 by abelov            #+#    #+#              #
#    Updated: 2026/03/20 05:43:01 by abelov           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:

  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: requirements/mariadb
    restart: always
    env_file: .env
    environment:
      DB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_DATABASE: ${DB_NAME}
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress:42
    build: requirements/wordpress
    restart: always
    env_file: .env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      REDIS_HOST: redis
    volumes:
      - wordpress:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx:42
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    secrets:
      - ssl_certificate
      - ssl_private_key
    networks:
      - inception
    depends_on:
      - wordpress

  redis:
    container_name: redis
    image: redis:42
    build: requirements/bonus/redis
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  ftp:
    container_name: ftp
    image: ftp:42
    build: requirements/bonus/ftp
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD_FILE: /run/secrets/ftp_password
    volumes:
      - wordpress:/home/${FTP_USER}/ftp/files
    secrets:
      - ftp_password
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    container_name: adminer
    image: adminer:42
    build: requirements/bonus/adminer
    restart: always
    ports:
      - "600:80"
    networks:
      - inception
    depends_on:
      - mariadb

  website:
    container_name: website
    image: website:42
    build: requirements/bonus/websites
    restart: always
    ports:
      - "3000:3000"
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    image: cadvisor:42
    build: requirements/bonus/cadvisor
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  ssl_certificate:
    file: ../secrets/certificate.crt
  ssl_private_key:
    file: ../secrets/private.key

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/abelov/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/abelov/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge
    name: inception
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
